### ISSUE TITLE
Alexa Youtube issue 

### ISSUE THREAD

**Issue by marlon1144** [reger-men/Alexa_YouTube#1]
Hi,
I have followed your tutorial but have two problems , hope you can help:
1. When uploading zip file (size is 2.5MB) there is an error with opening file , says coul d not find file index.js
    Not sure what I`m doing wrong here ?

![aws index jc error](https://user-images.githubusercontent.com/38840835/39409701-b258f5e0-4be3-11e8-9d8d-4930eed03079.PNG)

2. Obviously because of the issue with index.js when I go to test my Alexa skill and type in "Ask youtube for hello" , there is no contents on JSON Output side , and the following error is announced : " There was a problem with the requested skill response"

![there was a problem](https://user-images.githubusercontent.com/38840835/39409706-beaca170-4be3-11e8-9265-187a3996431e.PNG)

Could you please help - thanks in advance.

**Comment by reger-men** [comment]
Please note, that you have to upload the ZIP file, that contains only (as you can see in youtube video) "index.js, package.json, responses.js and node_modules"

1. Download this repository
2. Create ZIP file of  "index.js, package.json, responses.js and node_modules"
3. Upload the created ZIP file in AWS

**Comment by marlon1144** [comment]
Hi,

Thank you - it seems to be working finally.
However I have one issue, when asking alexa to search youtube music , I get response back in German: "Ich spiele jetzt Elton John - Nikita" 
Could you please advise how to rectify it ? It should say "I play now" in english

Below is the screeshot what I`m seeing when testing alexa skill

![german](https://user-images.githubusercontent.com/38840835/39411601-213c8370-4c05-11e8-8c96-1bd0f3a6434d.PNG)

**Comment by reger-men** [comment]
It should be solved now. Please check out this file: https://github.com/reger-men/Alexa_YouTube/blob/master/Interaction-Model.json
