### ISSUE TITLE
Stolen (?) Code

### ISSUE THREAD

**Issue by dmhacker** [reger-men/Alexa_YouTube#10]
Hello,

Hi, I'm David, the [original author of the Alexa YouTube skill](https://github.com/dmhacker/alexa-youtube-skill) that this project is based off of. It has come to my attention that this project is simply my own with some playlist functionality added. Looking through the code confirms my suspicions. I see you have scrubbed it clean of my name.

That being said, I would like you to make two modifications to your spinoff:

1.  Credit me in your README with a link to my repository (the original code) and add my name.
2. Change your license from the GNU GPL v3.0 to the MIT license, as the MIT license in my project stipulates that it must appear in modified copies.

If you do not comply with this request in 7 days, I will ask GitHub to take down the repository via a DMCA request, as it is within my legal jurisdiction to do so. I am not asking you to delete your project, as adding playlist functionality is pretty neat, but I feel I am justified in saying that you should give credit where it is due. In the future, note that plagiarizing work can be a serious offense.

Thank you.

As a side note, I would also like you to do the same with the server portion of this project. That could potentially be even more legally serious, as I retain all of the rights to that code without mention of an explicit license.

**Comment by reger-men** [comment]
Hi David, nice to hear from you. I suppose you haven't check that I credit you since the upload of this project. You can see the link to your project and there's a hint that the project is based on it in the description of the video, otherwise you would not have called as stolen. Thanks.

**Comment by dmhacker** [comment]
@reger-men 

I am not sure why this was closed, because you still haven't addressed my issues.

1. The MIT license in your source code needs to be an EXACT COPY of [mine](https://github.com/dmhacker/alexa-youtube-skill/blob/master/LICENSE). You cannot copyright my code as your own; that is intellectual property theft.
2. In your README, you stated that: "... Some functions were taken over from here". Most of the code you are using is my own still; you didn't just "take some functions". I said you should add my name and credit me with link, something like "This repository is based off of an original skill done by David Hacker: ..." 

Again, I will make sure this repository is taken down, lest you follow through. My demands really aren't hard to make, and seeing as how I've developed this over the course of two years (v.s. yours over a couple of days), I'd really appreciate it.

**Comment by dmhacker** [comment]
Yeah, that's good. Thanks!
