### ISSUE TITLE
doesnt work anymore :(

### ISSUE THREAD

**Issue by mc-chick** [reger-men/Alexa_YouTube#14]
get the error:
"Error retrieving device rendering
The object provided is not a valid template" 
in the Test section of the alexa developer console ...

test via alexa also doesn't work, the blue ring disapears some seconds after the order ...

**Comment by reger-men** [comment]
1. Download the last release version (ZIP file) from [Here ](https://github.com/reger-men/Alexa_YouTube/releases) and upload it in AWS. 
2. Follow the instructions in video.


If it still does not work, then please insert the exact error message here and the instruction that makes the issue appear.

**Comment by mc-chick** [comment]
thanks - everything fine now. maybe there was some older files on my harddisk ;)
