### ISSUE TITLE
cannot create a playlist

### ISSUE THREAD

**Issue by clipol** [reger-men/Alexa_YouTube#15]
Hi,
First of all thank you for the skill - it's working great. However when I try to add a certain song to a playlist I get a response in German "Ich spiele jetzt "Hello"..."  (why is it in German, not English?)
It seems like the playlist functionality is not working for me at all ;(
Pls help.

**Comment by reger-men** [comment]
Thank you for reporting this issue. I'll take a closer look.

**Comment by reger-men** [comment]
Please use the last release version [last release version](https://github.com/reger-men/Alexa_YouTube/releases) The playlist issue should be fixed now. Thanks!


Feel free to reopen if the issue still occurs.
