### ISSUE TITLE
timeout of 61000ms exceeded

### ISSUE THREAD

**Issue by ghost** [reger-men/Alexa_YouTube#2]
I tried uploading the zip file but I'm always getting the error 'timeout of 61000ms exceeded'. I even tried following steps from other forums to upload the zip file on S3 and point that URL to Lambda, but it still not working. I'm new to this but I know how to follow step by step instructions. I badly need help! Thanks in advance!

**Comment by reger-men** [comment]
Please make sure that you try to upload the right zip file.
See this one [here](https://github.com/reger-men/Alexa_YouTube/issues/1)

For timeout issue in S3, please see this [one](https://github.com/serverless/serverless/issues/490)

**Comment by ghost** [comment]
wow! that was fast. I appreciate the help. I'm looking into it now. Thanks!

**Comment by ghost** [comment]
I encountered the same error message when I tried uploading the zip file, but after I refresh the page I noticed that the files are already present. I tried playing some music, and Voila! It played! Thank you so much!

**Comment by reger-men** [comment]
You're Welcome.
