### ISSUE TITLE
songs suddenly stop playing

### ISSUE THREAD

**Issue by ghost** [reger-men/Alexa_YouTube#3]
I was so happy when I was able to make it work but now I've experienced this problem sporadically where song suddenly stops playing. I'm not sure if this relates to having my own server for the YouTube Api or is it something else. I need help. Thanks in advance

**Comment by reger-men** [comment]
Iam note sure what is the cause, but I can check if this issue from the Youtube API or my Webserver.
If you use my Webserver, please run a query via your Alexa. 

I can only see what happens **within 15min** after your run. So please let me know immediately after you run the query.

**Comment by ghost** [comment]
I apologize for the late response. I'm currently at work. I tried playing now and then it stopped in the middle of the song. It's a hit or miss now

**Comment by reger-men** [comment]
could you please try again.

**Comment by ghost** [comment]
Sorry. Just arrived from work. I tried it and it stopped again in the middle of the song

**Comment by reger-men** [comment]
So i just checked the webserver ad it work fine. Iam not sure what the problem is.

**Comment by ghost** [comment]
thanks for checking it. hmmm. i guess i'll try creating my own webserver?

**Comment by reger-men** [comment]
run it one more time please

**Comment by ghost** [comment]
to make sure I'm doing it right? I just need to run the command, right?

**Comment by reger-men** [comment]
you have only to ask Alexa for song title.

**Comment by ghost** [comment]
Thanks man. That's what I did just now. Playing Nirvana now

**Comment by reger-men** [comment]
you can check here your song: Only available for the next 5min
https://youtube-alexa.herokuapp.com/public/site/hTWKbfoikeg.m4a

**Comment by ghost** [comment]
It stopped immediately before the chorus :(

**Comment by ghost** [comment]
Thanks for your help. I'll just try changing the settings of the app

**Comment by ghost** [comment]
I tried creating my own heroku server but it seems that the problem is still there. I did my own testing and noticed that it stops after 2 minutes. Could it be possible that the problem is somehow related to using "free" server from heroku?
