### ISSUE TITLE
Alexa-Simulator gibt keine Antwort...

### ISSUE THREAD

**Issue by viodic** [reger-men/Alexa_YouTube#8]
Ich habe das Youtube-Video und die Github-Anleitung versucht umzusetzen. Bis zum Testen mit dem Alexa-Simulator gab es keine Fehlermeldungen.  Beim Test gib Alexa keine Antwort.. Anbei befinden sich zwei Bilder. Wo ran könnte es liegen? 
![fehleryoutube](https://user-images.githubusercontent.com/45365102/49028007-bac06600-f1a1-11e8-9f3b-e320e9a82c15.jpg)
![aws_eingabe_youtube](https://user-images.githubusercontent.com/45365102/49028022-bf851a00-f1a1-11e8-93fa-d5ceb01e7489.jpg)

**Comment by reger-men** [comment]
Thank you @viodic for your report! I will take a closer look at it. This may happen in the next weekend.

**Comment by reger-men** [comment]
#4
